/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalaxiaFormIdRouteImport } from './routes/galaxia.$formId'
import { Route as GalaxiaFormIdVictoriaLevelIdRouteImport } from './routes/galaxia_.$formId_.victoria.$levelId'
import { Route as GalaxiaFormIdNivelLevelIdRouteImport } from './routes/galaxia_.$formId_.nivel.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxiaFormIdRoute = GalaxiaFormIdRouteImport.update({
  id: '/galaxia/$formId',
  path: '/galaxia/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxiaFormIdVictoriaLevelIdRoute =
  GalaxiaFormIdVictoriaLevelIdRouteImport.update({
    id: '/galaxia_/$formId_/victoria/$levelId',
    path: '/galaxia/$formId/victoria/$levelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GalaxiaFormIdNivelLevelIdRoute =
  GalaxiaFormIdNivelLevelIdRouteImport.update({
    id: '/galaxia_/$formId_/nivel/$levelId',
    path: '/galaxia/$formId/nivel/$levelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galaxia/$formId': typeof GalaxiaFormIdRoute
  '/galaxia/$formId/nivel/$levelId': typeof GalaxiaFormIdNivelLevelIdRoute
  '/galaxia/$formId/victoria/$levelId': typeof GalaxiaFormIdVictoriaLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galaxia/$formId': typeof GalaxiaFormIdRoute
  '/galaxia/$formId/nivel/$levelId': typeof GalaxiaFormIdNivelLevelIdRoute
  '/galaxia/$formId/victoria/$levelId': typeof GalaxiaFormIdVictoriaLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galaxia/$formId': typeof GalaxiaFormIdRoute
  '/galaxia_/$formId_/nivel/$levelId': typeof GalaxiaFormIdNivelLevelIdRoute
  '/galaxia_/$formId_/victoria/$levelId': typeof GalaxiaFormIdVictoriaLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galaxia/$formId'
    | '/galaxia/$formId/nivel/$levelId'
    | '/galaxia/$formId/victoria/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galaxia/$formId'
    | '/galaxia/$formId/nivel/$levelId'
    | '/galaxia/$formId/victoria/$levelId'
  id:
    | '__root__'
    | '/'
    | '/galaxia/$formId'
    | '/galaxia_/$formId_/nivel/$levelId'
    | '/galaxia_/$formId_/victoria/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalaxiaFormIdRoute: typeof GalaxiaFormIdRoute
  GalaxiaFormIdNivelLevelIdRoute: typeof GalaxiaFormIdNivelLevelIdRoute
  GalaxiaFormIdVictoriaLevelIdRoute: typeof GalaxiaFormIdVictoriaLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxia/$formId': {
      id: '/galaxia/$formId'
      path: '/galaxia/$formId'
      fullPath: '/galaxia/$formId'
      preLoaderRoute: typeof GalaxiaFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxia_/$formId_/victoria/$levelId': {
      id: '/galaxia_/$formId_/victoria/$levelId'
      path: '/galaxia/$formId/victoria/$levelId'
      fullPath: '/galaxia/$formId/victoria/$levelId'
      preLoaderRoute: typeof GalaxiaFormIdVictoriaLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxia_/$formId_/nivel/$levelId': {
      id: '/galaxia_/$formId_/nivel/$levelId'
      path: '/galaxia/$formId/nivel/$levelId'
      fullPath: '/galaxia/$formId/nivel/$levelId'
      preLoaderRoute: typeof GalaxiaFormIdNivelLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalaxiaFormIdRoute: GalaxiaFormIdRoute,
  GalaxiaFormIdNivelLevelIdRoute: GalaxiaFormIdNivelLevelIdRoute,
  GalaxiaFormIdVictoriaLevelIdRoute: GalaxiaFormIdVictoriaLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
